openapi: 3.0.0

info:
    title: CyberFuse
    description: CyberFuse AI SecLM Skillset to prompt and provide insights and context analysis across the CyberFuse connected data sources.
    version: 1.0.0

servers:
    - url: http://20.55.88.26:8001/

paths:
    /chat/stream:
        post:
            operationId: CyberFuseAIPrompt
            summary: Submit a prompt
            parameters:
                - in: query
                  name: content
                  schema:
                      type: string
                  required: true
                  description: The Prompt content
                - in: query
                  name: type
                  schema:
                      type: string
                  default: human
                  description: Please do not change, the value should be human

            responses:
                "200":
                    description: OK