openapi: 3.0.0

info:
  title: "EchoTrail Insights reports"
  description: "EchoTrail Insights reports"
  version: "v1"

servers:
  - url: "https://api.echotrail.io/"

paths:
  /insights/{query}:
    get:
      operationId: "EchoTrailInsightsFullSummary"
      summary: "Get a full summary of a requested filename or hash"
      parameters:
        - in: "path"
          name: "query"
          schema:
            type: "string"
          required: true
          description: "The name or hash of an endpoint process to lookup. Must be a Windows filename with extension or a SHA256 hash of a Windows process or an MD5 hash of a Windows process"
      responses:
        "200":
          description: "OK"

  /insights/{query}/{field}:
    get:
      operationId: "EchoTrailInsightsFieldSearch"
      summary: "Get one particular field from the results of a process search. Useful for efficiently fetching data when you only need one field."
      parameters:
        - in: "path"
          name: "query"
          schema:
            type: "string"
          required: true
          description: "The name or hash of an endpoint process to lookup. Must be a Windows filename with extension or a SHA256 hash of a Windows process or an MD5 hash of a Windows process"
        - in: "path"
          name: "field"
          schema:
            type: "string"
          required: true
          description: "Must be one of the following: description, rank, host_prev, eps, parents, children, grandparents, hashes, paths, network, or intel"
      responses:
        "200":
          description: "OK"

  /insights/{query}/{field}/{subsearch}:
    get:
      operationId: "EchoTrailInsightsSubSearch"
      summary: "Perform a search within a list of results from a process search. For example, searching for a particular port in the network table of the cmd.exe process."
      parameters:
        - in: "path"
          name: "query"
          schema:
            type: "string"
          required: true
          description: "The name or hash of an endpoint process to lookup. Must be a Windows filename with extension or a SHA256 hash of a Windows process or an MD5 hash of a Windows process"
        - in: "path"
          name: "field"
          schema:
            type: "string"
          required: true
          description: "Must be one of the following: description, rank, host_prev, eps, parents, children, grandparents, hashes, paths, network, or intel"
        - in: "path"
          name: "subsearch"
          schema:
            type: "string"
          required: true
          description: "The string to search for within the process field"
      responses:
        "200":
          description: "OK"