openapi: 3.0.0
info:
  title: Cortex XDR API
  description: Retrieve incidents from Cortex XDR with simplified parameters.
  version: "1.0.0"
servers:
  - url: https://<URL?.com

paths:
  /public_api/v1/incidents/get_incidents/:
    post:
      summary: Get All Incidents
      description: Retrieve a list of incidents from Cortex XDR.
      operationId: getAllIncidents
      parameters:
        - in: header
          name: <Key-ID>
          schema:
            type: string
          required: true
          description: Default is 
        - name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            example: 50
        - name: sort
          in: query
          required: false
          schema:
            type: string
            example: "desc"
      responses:
        '200':
          description: Successful retrieval of incidents.
          content:
            application/json:
              schema:
                type: object
                properties:
                  incident_id:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  creation_time:
                    type: string
                    format: date-time
                  last_modified:
                    type: string
                    format: date-time
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '500':
          description: Internal server error.

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key  # This is for the API key
    xdrAuthId:
      type: apiKey
      in: header
      name: x-xdr-auth-id  # This is for the API key ID

security:
  - apiKeyAuth: []
  - xdrAuthId: []