openapi: 3.0.1
info:
  title: Trigger Azure Logic App
  version: 1.0.0
paths:
  /trigger:
    post:
      summary: Trigger the Azure Logic App
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: Message to send to Logic App
      responses:
        '200':
          description: Logic App triggered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
servers:
  - url:   https://prod-71.eastus.logic.azure.com:443/workflows/8f4c192bcb6045b1a0a3d497abf72e66/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=XlcSYB1Dy6i1bzA66ukEwXSKd2Yh83_uXPWN3fb7wK8
    description: Azure Logic App endpoint