openapi: 3.0.1
info:
  title: Send Email via Logic App
  description: API to send an email using an Azure Logic App HTTP trigger.
  version: 1.0.0
servers:
  - url: https://prod-19.northcentralus.logic.azure.com:443/workflows/1f47ee8fd7ef4f7e8c308f2107dd96a7/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=sEv0wd1-3lGBIMvtcvPmmGiQctVcG_lksvnLV8rD_ho
    description: Azure Logic App HTTP trigger endpoint
paths:
  /invoke:
    post:
      operationId: sendEmail
      summary: Sends an email via Logic App
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient:
                  type: string
                  description: Email address of the recipient
                subject:
                  type: string
                  description: Subject of the email
                message:
                  type: string
                  description: Body of the email
              required:
                - recipient
                - subject
                - message
      responses:
        '202':
          description: Email sent successfully
        '400':
          description: Bad request
        '500':
          description: Server error