openapi: 3.0.0
info:
    title: "text-to-visual-plugin"
    description: "The skill in this plugin will convert text to visual"
    version: 1.0.0

# This should point to the Azure Function URL
servers:
    - url: "https://seccopilottexttovisualfn.azurewebsites.net/api/"

paths:
    /ConvertTextToChart:
           post:
      summary: Generate a visual from text input
      operationId: ConvertTextToChart
      tags:
        - text-to-visual
      requestBody:
        description: Input data for generating the visual
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                inputText:
                  type: string
                  description: The text input to convert into a visual.
                style:
                  type: string
                  description: Optional style for the generated visual.
              required:
                - inputText
      responses:
        '200':
          description: Successful visual generation
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    description: URL of the generated visual.
        '400':
          description: Bad request, input validation failed
        '500':
          description: Server error
